language: python

python: 2.7
node_js: "4.1"

install:
    - travis_retry pip install -r requirements.txt
    - . $HOME/.nvm/nvm.sh
    - nvm install stable
    - nvm use stable
    - cd webpack; travis_retry npm install

script:
    - lektor build -f webpack
    - test "$TRAVIS_PULL_REQUEST" == false && test "$TRAVIS_BRANCH" == master && lektor deploy ghpages
